### ISSUE TITLE
Integrate Exam management

### ISSUE THREAD

**Issue by AhmadGlobusLabs** [Yogndrr/MERN-School-Management-System#7]
I want to integrate a exam management in your project.
Where teacher can add test and student gives exams.
I am currently working on it and it is about to complete. After that i will update it

**Comment by Yogndrr** [comment]
> I want to integrate a exam management in your project. Where teacher can add test and student gives exams. I am currently working on it and it is about to complete. After that i will update it

Ok do let me know
