### ISSUE TITLE
Implement User Authentication (Students, Teachers, Admin)

### ISSUE THREAD

**Issue by shruti01941704** [Yogndrr/MERN-School-Management-System#8]
Add login functionality for three roles: Students, Teachers, and Admins.
Each user should be able to log in and view their respective dashboard.
Use JWT for authentication and bcrypt for password encryption.

**Comment by Yogndrr** [comment]
> Add login functionality for three roles: Students, Teachers, and Admins. Each user should be able to log in and view their respective dashboard. Use JWT for authentication and bcrypt for password encryption.

What you are suggesting is already there in the system except for the JWT Authentication. I haven't worked on this project for a while. If you want to add that functionality then you can.
